stages:
  - install
  - test
  - deploy

# Usando a imagem base Ruby
image: ruby:3.1

# Job para instalar as dependências
install-dependencies:
  stage: install
  script:
    - echo "Instalando dependências..."
    # Instalando dependências básicas e Node.js
    - apt-get update -y
    - apt-get install -y curl gnupg2 ca-certificates lsb-release
    # Instalando o Node.js e npm
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -  # Configura o repositório do Node.js
    - apt-get install -y nodejs  # Instala o Node.js
    # Verificando as versões do Node.js e npm para garantir que estão instalados corretamente
    - node -v
    - npm -v
    - npm install  # Instala as dependências do projeto

# Job para rodar os testes Android no BrowserStack
test-android-browserstack:
  stage: test
  script:
    - echo "Executando testes Android no BrowserStack..."
    - npm run test:android:browserstack
  only:
    - master

# Job para rodar os testes iOS no BrowserStack
test-ios-browserstack:
  stage: test
  script:
    - echo "Executando testes iOS no BrowserStack..."
    - npm run test:ios:browserstack
  only:
    - master

# Job para gerar e exibir o relatório do Allure
allure-report:
  stage: deploy
  script:
    - echo "Gerando o relatório do Allure..."
    - npm run allure-report
  only:
    - master
