stages:
  - install
  - test
  - deploy

# Usando a imagem Docker com Node.js
image: node:22.11.0

# Job para instalar as dependências
install-dependencies:
  stage: install
  script:
    - echo "Instalando dependências..."
    - npm ci  # Instala as dependências com base no package-lock.json
    - npm audit fix --force  # Corrige vulnerabilidades automaticamente

# Job para rodar os testes Android no BrowserStack
test-local-and-browserstack:
  stage: test
  script:
    - echo "Executando testes Android no BrowserStack..."
    - package.json
  only:
    - master



# Job para gerar e exibir o relatório do Allure
allure-report:
  stage: deploy
  script:
    - echo "Gerando o relatório do Allure..."
    - npm run allure-report
  only:
    - master
