stages:
  - install
  - test
  - deploy

# Usando a imagem Docker com Node.js
image: node:22

variables:
  BROWSERSTACK_USERNAME: "lucasdeoliveiras_BCfDNo"
  BROWSERSTACK_ACCESS_KEY: "H6yDfhBWyi31rJu69oYd"
  NO_UPDATE_NOTIFIER: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Job para instalar as dependências
install-dependencies:
  stage: install
  script:
    - echo "Instalando dependências..."
    - npm ci

# Job para rodar os testes Android no BrowserStack
test-browserstack:
  stage: test
  script:
    - echo "Executando testes Android no BrowserStack..."
    - ./node_modules/.bin/wdio run ./config/wdio.conf.js
  only:
    - master

# Job para gerar e exibir o relatório do Allure
allure-report:
  stage: deploy
  script:
    - echo "Gerando o relatório do Allure..."
    - npm run allure-report  # Gerar o relatório do Allure
  only:
    - master
