stages:
  - install
  - test
  - deploy

image: node:22

variables:
  BROWSERSTACK_USERNAME: "lucasdeoliveiras_BCfDNo"
  BROWSERSTACK_ACCESS_KEY: "H6yDfhBWyi31rJu69oYd"
  NO_UPDATE_NOTIFIER: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - echo "Instalando dependências..."
    - npm ci

test-browserstack-android: 
  stage: test
  script:
    - echo "Definindo variáveis de ambiente para Android..."
    - export TEST_ENV=browserstack
    - export PLATFORM=android
    - echo "Executando testes Android no BrowserStack..."
    - ./node_modules/.bin/wdio run ./config/wdio.conf.js
  only:
    - master

test-browserstack-ios: 
  stage: test
  script:
    - echo "Definindo variáveis de ambiente para iOS..."
    - export TEST_ENV=browserstack
    - export PLATFORM=ios
    - echo "Executando testes iOS no BrowserStack..."
    - ./node_modules/.bin/wdio run ./config/wdio.conf.js 
  only:
    - master

allure-report:
  stage: deploy
  script:
    - echo "Instalando o Java necessário para o Allure..."
    - apt-get update && apt-get install -y openjdk-17-jre
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version
    - echo "Gerando o relatório do Allure..."
    - ./node_modules/.bin/allure generate allure-results --clean
    - ./node_modules/.bin/allure open
  only:
    - master