stages:
  - test

variables:
  BROWSERSTACK_USERNAME: "lucasdeoliveiras_BCfDNo"
  BROWSERSTACK_ACCESS_KEY: "H6yDfhBWyi31rJu69oYd"

before_script:
  - npm ci

test_android_browserstack:
  stage: test
  script:
    - npm run test:android:browserstack
  tags:
    - android-test