stages:
  - install
  - test
  - deploy

# Usando a imagem Docker com Node.js
image: node:22

# Job para instalar as dependências
install-dependencies:
  stage: install
  script:
    - echo "Instalando dependências..."
    - npm ci  # Instala as dependências com base no package-lock.json

# Job para rodar os testes Android no BrowserStack
test-browserstack:
  stage: test
  script:
    - echo "Executando testes Android no BrowserStack..." 
    - npm run testrun:android:browserstack
  only:
    - master

# Job para gerar e exibir o relatório do Allure
allure-report:
  stage: deploy
  script:
    - echo "Gerando o relatório do Allure..."
    - npm run allure-report  # Gerar o relatório do Allure
  only:
    - master
