stages:
  - test

variables:
  BROWSERSTACK_USERNAME: "lucasdeoliveiras_BCfDNo"
  BROWSERSTACK_ACCESS_KEY: "H6yDfhBWyi31rJu69oYd"
  NO_UPDATE_NOTIFIER: 1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

test_android_browserstack:
  stage: test
  script:
    - ./node_modules/.bin/wdio run ./config/wdio.conf.js
  tags:
    - android-test
