stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-android-local:
  stage: test
  before_script:
    # Instalar Node.js e npm
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - echo "Running Android tests locally..."
    - npm run test:android:local
  only:
    - master

test-ios-local:
  stage: test
  before_script:
    # Instalar Node.js e npm
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - echo "Running iOS tests locally..."
    - npm run test:ios:local
  only:
    - master

test-android-browserstack:
  stage: test
  before_script:
    # Instalar Node.js e npm
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - echo "Running Android tests on BrowserStack..."
    - npm run test:android:browserstack
  only:
    - master

test-ios-browserstack:
  stage: test
  before_script:
    # Instalar Node.js e npm
    - apt-get update
    - apt-get install -y nodejs npm
  script:
    - echo "Running iOS tests on BrowserStack..."
    - npm run test:ios:browserstack
  only:
    - master

allure-report:
  stage: deploy
  script:
    - npm run allure-report
  only:
    - master
